name: portfolio-deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      #Get access to your portfolio code via pre built action
      #Clone the code from github
      #Step = 1
      - name: checkout code
        uses: actions/checkout@v4

      #Step = 2
      #Setup Github pages
      - name: Setup github pages
        uses: actions/configure-pages@v4

      #Step = 3
      #Static code artifacts
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "." #Path to your static code artifacts, in this case the root directory of the repository

      #Step = 4
      #Deploy to Github pages
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4
        with:
          url: ${{ steps.deploy-pages.outputs.page_url }}
