name: portfolio-deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      #Get access to your portfolio code via pre built action
      #Clone the code from github

      #Step = 1 Checkout repository code
      - name: checkout code
        uses: actions/checkout@v4

      # Step 2 - Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #Step = 3 Install dependencies and build the code
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      #Step = 4 Build the code
      - name: Build Project
        run: |
          cd frontend
          npm run build

      #Step= 5 Setup Github pages
      - name: Setup github pages
        uses: actions/configure-pages@v4

      #Step = 6 Upload build folder
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./frontend/build" #Path to your static code artifacts, in this case the root directory of the repository

      #Step = 7 Deploy to Github pages
      - name: Deploy to Github pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
        with:
          page_url: ${{ steps.deploy-pages.outputs.page_url }}
